# Generated by Django 3.0 on 2023-02-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/', verbose_name='Картинка')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='places', to='places.Image', verbose_name='Изображение'),
        ),
    ]
