# Generated by Django 3.0 on 2023-02-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20230203_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Image')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
            options={
                'ordering': ['images_order'],
            },
        ),
        migrations.RemoveField(
            model_name='place',
            name='images',
        ),
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='places', through='places.ImagesPlace',
                                         to='places.Image', verbose_name='Изображение'),
        )
    ]
