# Generated by Django 3.0 on 2023-03-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20230303_0249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesPlace',
        ),
    ]
