# Generated by Django 3.0 on 2023-03-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_delete_imagesplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('pk',)},
        ),
    ]
