# Generated by Django 3.0 on 2023-03-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20230306_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='image',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
