# Generated by Django 3.0 on 2023-03-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20230306_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='my_order',
            new_name='order',
        ),
    ]
